
<div id="<?php echo $this->getContainerId(); ?>">

    <div class="entry-edit" id="magento_block_synchronization_inspector">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Track Direct Database Changes'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="inspector_mode"><?php echo Mage::helper('M2ePro')->__('Enabled'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" colspan="2">
                            <select id="inspector_mode" name="inspector_mode">
                                <option value="0"<?php if ($this->inspectorMode == 0) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                <option value="1"<?php if ($this->inspectorMode == 1) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__("Should be enabled if changes in catalog is being made directly to database.<br/><b>Note:</b> It is strongly recommended to enable this option if you really need it,<br/>as it is very resource and time consuming and may have affect on<br/>synchronization performance."); ?></span>
                            </p>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

</div>