<?php if($this->getItems()->getSize()): ?>
<div class="block-related-wrapper">
  <div class=" block block-related block-related-tabbed">
   <div class="pane">
    <div class="block-title"><strong><span><?php echo $this->__('Customer Choices') ?></span></strong></div>
    <div class="block-content">
    <?php foreach ($this->getItems() as $_item): ?>
      <ol class="mini-products-list">
        <li class="item">
         <div class="product">
            <a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(75); ?>" width="56" height="56" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
            <div class="product-details">
                <h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></h3>
                <?php echo $this->getPriceHtml($_item, true) ?>
            </div>
         </div>   
        </li>
      </ol>
    <?php endforeach; ?>
    </div>
    <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
   </div>
  </div>
</div>
<?php endif; ?>
