
<script src="<?php echo $this->getSkinUrl('js/count.js') ?>" language="javascript"></script>

     <div style="padding-left: 50px; padding-top: 30px; font-weight: bold; font-size: 14px; color:#000;">
           --------- JAVASCRIPT COUNTDOWN TIMER ------------
     </div>          
               <div class="hit_count" style="padding-left: 130px; padding-top: 30px; font-weight: bold; font-size: 35px; color:#000; word-spacing: -6px;">
                    <span id="cd"></span> 
               </div>
                    