<div id="block_notice_amazon_accounts_general" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('General'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Fill the title, choose Marketplace you need and click <i>Get Access Data</i> link. You will be redirected to the Amazon website. Sign-in and complete step of getting access. The Merchant ID and Marketplace ID will be generated and shown on the next page. Copy them and paste in corresponding fields of current page.
<br/>Press <span style="text-decoration: underline;">Save And Continue Edit</span>.
<br/><br/>After saving you will see additional settings tabs under Configuration in the left side menu.'); ?>
</div>

<?php
    $formData = Mage::helper('M2ePro')->getGlobalValue('temp_data') ? Mage::helper('M2ePro')->getGlobalValue('temp_data')->toArray() : array();

    if (isset($formData['other_listings_mapping_settings'])) {
        $formData['other_listings_mapping_settings'] = (array)json_decode($formData['other_listings_mapping_settings'],true);
    }

    $defaults = array(
        'title' => ''
    );

    $formData = array_merge($defaults, $formData);

    $isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.text = {};
    }

    M2ePro.url.formSubmit = '<?php echo $this->getUrl('*/*/save', array('id' => $this->getRequest()->getParam('id'))); ?>';
    M2ePro.url.deleteAction = '<?php echo $this->getUrl('*/*/delete', array('id' => $this->getRequest()->getParam('id'))); ?>';
    
    M2ePro.formData.id = '<?php echo $this->getRequest()->getParam('id'); ?>';

    Event.observe(window, 'load', function() {
        AmazonAccountHandlerObj = new AmazonAccountHandler();
        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });
    //-----------------------------

</script>

<script type="text/javascript">

    // Data for current tab
    //-----------------------------
    M2ePro.formData.title = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->escapeHtml($formData['title'])); ?>';

    M2ePro.text.title_not_unique_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The specified title is already used for other account. Account title must be unique.')); ?>';
    M2ePro.text.need_select_marketplaces_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('You must enable marketplace(s) first.')); ?>';

    Event.observe(window, 'load', function() {
        AmazonAccountHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Amazon_Account'); ?>');
    });
    //-----------------------------
    
</script>

<div class="entry-edit" id="magento_block_amazon_accounts_general_general">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="title"><?php echo Mage::helper('M2ePro')->__('Title'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <input id="title" name="title" value="<?php echo $this->escapeHtml($formData['title']); ?>" type="text" class="input-text required-entry M2ePro-account-title" />
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Title or identifier of Amazon account for your internal use.'); ?></span>
                        </p>
					</td>
                </tr>

            </table>
            
        </div>
    </div>

</div>

<?php if ($this->synchronizeProcessing) { ?>
    <div class="locked_block">

        <div class="locked_wrapper">
            <div><?php echo Mage::helper('M2ePro')->__('Synchronizing Now') ?></div>
        </div>
<?php } ?>

<div class="entry-edit" id="magento_block_amazon_accounts_marketplaces_access" collapseable="no">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Marketplaces'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <?php if (count($this->marketplaces) <= 0) { ?>

                <div id="block_notice_amazon_accounts_general_marketplaces_access_none" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('None Marketplaces'); ?>" collapseable="no" always_show="yes" hideblock="no">
                    <?php echo Mage::helper('M2ePro')->__('You should select and update eBay marketplaces to get access to this section.'); ?>
                </div>

                <input type="hidden" name="validate_selected_marketplaces" value="" class="M2ePro-require-select-marketplaces" />

            <?php } else { ?>

                <?php if (!$this->synchronizeProcessing) { ?>
                    <input type="hidden" name="validate_selected_marketplaces" value="" class="M2ePro-require-select-marketplaces" />
                <?php } ?>

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <?php foreach ($this->marketplaces as $marketplaceRow) { ?>

                        <tr>
                            <td class="label">
                                <label><?php echo $marketplaceRow['title'] ?> (<?php echo $marketplaceRow['url'] ?>):</label>
                            </td>
                            <td class="value" style="width: auto;">

                                <?php if ($marketplaceRow['locked']) { ?>
                                    <input type="hidden" name="marketplace_mode_<?php echo $marketplaceRow['id']; ?>" value="1" />
                                    <select disabled="disabled" name="fake_marketplace_mode_<?php echo $marketplaceRow['id']; ?>" class="locked_selected marketplace_mode_select">
                                        <option value="1" selected="selected"><?php echo Mage::helper('M2ePro')->__('Enabled'); echo ' - '.Mage::helper('M2ePro')->__('Used in Listing(s)'); ?></option>
                                    </select>
                                <?php } else { ?>
                                    <select id="marketplace_mode_<?php echo $marketplaceRow['id']; ?>" name="marketplace_mode_<?php echo $marketplaceRow['id']; ?>" onchange="AmazonAccountHandlerObj.changeMarketplaceMode('<?php echo $marketplaceRow['id']; ?>');"  <?php if ($marketplaceRow['account_data']['mode']) echo ' class="hightlight_selected marketplace_mode_select"'; else echo ' class="lacklustre_selected marketplace_mode_select"'; ?>>
                                        <option value="0"<?php if (!$marketplaceRow['account_data']['mode']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Disabled'); ?></option>
                                        <option value="1"<?php if ($marketplaceRow['account_data']['mode']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Enabled'); ?></option>
                                    </select>
                                <?php } ?>

                            </td>
                        </tr>

                        <tr id="marketplaces_register_url_container_<?php echo $marketplaceRow['id']; ?>" <?php if (!$marketplaceRow['account_data']['mode']) echo ' style="display:none;"'; ?>>
                            <td class="label"></td>
                            <td class="value" style="width: auto;">
                                <?php if (!$marketplaceRow['account_data']['mode']) { ?>
                                    <a href="<?php echo $marketplaceRow['account_data']['register_url']; ?>" target="_blank"><?php echo Mage::helper('M2ePro')->__('Get Access Data') ?></a>
                                <?php } ?>
                            </td>
                        </tr>

                        <tr id="marketplaces_application_name_container_<?php echo $marketplaceRow['id']; ?>" <?php if (!$marketplaceRow['account_data']['mode']) echo ' style="display:none;"'; ?>>
                            <?php if (!$marketplaceRow['account_data']['mode']) { ?>
                                <td class="label"><?php echo Mage::helper('M2ePro')->__('Application Name') ?>:</td>
                                <td class="value" style="width: auto;"><?php echo $marketplaceRow['application_name'] ?></td>
                            <?php } ?>
                        </tr>

                        <tr id="marketplaces_developer_key_container_<?php echo $marketplaceRow['id']; ?>" <?php if (!$marketplaceRow['account_data']['mode']) echo ' style="display:none;"'; ?>>
                            <?php if (!$marketplaceRow['account_data']['mode']) { ?>
                                <td class="label"><?php echo Mage::helper('M2ePro')->__('Developer Account Number') ?>:</td>
                                <td class="value" style="width: auto;"><?php echo $marketplaceRow['developer_key'] ?></td>
                            <?php } ?>
                        </tr>

                        <tr id="marketplaces_merchant_id_container_<?php echo $marketplaceRow['id']; ?>" <?php if (!$marketplaceRow['account_data']['mode']) echo ' style="display:none;"'; ?>>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Merchant ID'); ?>: <span class="required">*</span></label>
                            </td>
                            <td class="value" style="width: auto;">
                                <input type="text" name="marketplace_merchant_id_<?php echo $marketplaceRow['id']; ?>" value="<?php echo $marketplaceRow['account_data']['merchant_id']; ?>" class="input-text M2ePro-required-when-visible" />
                            </td>
                        </tr>

                        <tr id="marketplaces_marketplace_id_container_<?php echo $marketplaceRow['id']; ?>" <?php if (!$marketplaceRow['account_data']['mode']) echo ' style="display:none;"'; ?>>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Marketplace ID'); ?>: <span class="required">*</span></label>
                            </td>
                            <td class="value" style="width: auto;">
                                <input type="text" name="marketplace_marketplace_id_<?php echo $marketplaceRow['id']; ?>" value="<?php echo $marketplaceRow['account_data']['marketplace_id']; ?>" class="input-text M2ePro-required-when-visible" />
                            </td>
                        </tr>

                        <tr id="marketplaces_related_store_id_container_<?php echo $marketplaceRow['id']; ?>" <?php if (!$marketplaceRow['account_data']['mode']) echo ' style="display:none;"'; ?>>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Related Store View'); ?>: <span class="required">*</span></label>
                            </td>
                            <td class="value" style="width: auto;">
                                <?php
                                    $tempStoreBlock = $this->getLayout()->createBlock('M2ePro/adminhtml_storeSwitcher', '', array('id'=>'marketplace_related_store_id_'.$marketplaceRow['id'],'selected' => $marketplaceRow['account_data']['related_store_id']));
                                    echo $tempStoreBlock->toHtml();
                                ?>
                            </td>
                        </tr>

                        <tr>
                            <td class="value" colspan="2" style="width: auto;">
                                <hr style="border: 1px solid silver; border-bottom: none;"/>
                            </td>
                        </tr>

                    <?php } ?>

                <?php } ?>

            </table>

        </div>
    </div>

</div>

<?php if ($this->synchronizeProcessing) { ?>
    </div>
<?php } ?>