<?php 
/**
 * @category    Mana
 * @package     ManaPro_FilterShowMore
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/** 
 * Template for showing Show More / Show less actions 
 * @author Mana Team
 * Injected in designated place in filter items template used. In default template, designated place is right 
 * under list of items
 */
/* @var $block Mana_Filters_Block_Filter_Attribute */
?>
<?php /* @var $_helper ManaPro_FilterShowMore_Helper_Data */ $_helper = Mage::helper(strtolower('ManaPro_FilterShowMore'));?>
<?php /* @var $_filter Mana_Filters_Model_Filter_Attribute */ $_filter = $block->getFilter();?>
<?php if ($_filter->getMIsShowMoreApplied()) : ?>
<div class="m-more-less" id="m-more-less-<?php echo $_filter->getFilterOptions()->getCode() ?>">
	<?php if (Mage::getStoreConfigFlag('mana_filters/display/show_more_preload')) : ?>
	    <?php if (Mage::getStoreConfig('mana_filters/display/show_more_method') == 'scrollbar') : ?>
        <script type="text/javascript">(function ($) {
            $(document).trigger('m-filter-scroll-reset', [
                '<?php echo $_filter->getFilterOptions()->getCode() ?>',
                <?php echo $_filter->getFilterOptions()->getShowMoreItemCount() ?>
            ]);
        })(jQuery);</script>
        <?php else : ?>
		<a class="m-show-less-action" href="#"><?php echo $block->__('Show Less') ?></a>
		<a class="m-show-more-action" href="#"><?php echo $block->__('Show More') ?></a>
		<script type="text/javascript">(function($) {
			$(document).trigger('m-show-more-reset', [
				'<?php echo $_filter->getFilterOptions()->getCode() ?>',
				<?php echo $_filter->getFilterOptions()->getShowMoreItemCount() ?>,
				<?php echo $_helper->isShowAllRequested($_filter) ? 'true' : 'false' ?>,
				<?php echo Mage::getStoreConfig('mana_filters/display/show_more_time') ?>
			]);
		})(jQuery);</script> 
		<?php endif; ?>
	<?php else: ?>
		<?php if ($_helper->isShowAllRequested($_filter)) : ?>
		<a href="<?php echo $block->urlEscape($_helper->getShowLessUrl($_filter)) ?>"><?php echo $block->__('Show Less') ?></a>
		<?php else : ?>
		<a href="<?php echo $block->urlEscape($_helper->getShowMoreUrl($_filter)) ?>"><?php echo $block->__('Show More') ?></a>
		<?php endif; ?>
	<?php endif; ?>
</div>
<?php endif; ?>

