<?php if ($this->paymentMethod) { ?>
<?php echo $this->paymentMethod; ?>{{pdf_row_separator}}
<?php } ?>

<?php if ($this->channelOrderId) { ?>
<?php echo Mage::helper('M2ePro')->__('Order ID') . ': ' . $this->channelOrderId ?>{{pdf_row_separator}}
<?php } ?>

<?php if ($this->channelFinalFee) { ?>
<?php echo Mage::helper('M2ePro')->__('Fee') . ': ' . $this->channelFinalFee ?>{{pdf_row_separator}}
<?php } ?>

<?php if (!empty($this->transactions)) { ?>
<?php echo Mage::helper('M2ePro')->__('Transaction') ?>: {{pdf_row_separator}}

<?php foreach ($this->transactions as $key => $transaction) { ?>
<?php echo Mage::helper('M2ePro')->__('Transaction ID') . ': ' . $transaction['transaction_id']; ?>{{pdf_row_separator}}
<?php echo Mage::helper('M2ePro')->__('Transaction Date') . ': ' . Mage::helper('core')->formatDate($transaction['transaction_date'], 'medium', true); ?>{{pdf_row_separator}}
<?php } ?>

<?php } ?>