<div id="block_notice_marketplaces_choose" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Marketplaces'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This section allows you to set up Marketplaces you will work with.<br/>
    Enable certain marketplaces and press the <u>Save And Update</u> button in the top right corner, all necessary marketplace data will be downloaded and synchronized with settings.<br/><br/>
	It is recommended to update marketplaces when any marketplace changes are announced. <br/><br/>
	<b>Note:</b> Installation and update processes might be time-consuming, depending on the number of enabled marketplaces and your server environment. <br/>
	'); ?>
</div>