<div id="<?php echo $this->getContainerId(); ?>" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('3rd Party Listings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This section contains Amazon Listings, which belong to registered Amazon Accounts (Amazon > Configuration > Amazon Accounts)
	and were listed not by M2E Pro extension.<br/>
	Use Amazon Accounts and Marketplaces dropdowns to filter them.
	Also, you can manage these Listings on Amazon by choosing appropriate options in the Actions dropdown in the top right corner of the grid.<br/><br/>
	<b>Note:</b> To import Amazon 3rd Party Listings the 3rd Party Listings Import should be enabled in account\'s settings 
	(Amazon > Configuration > Amazon Accounts > General tab) and the 3rd Party Listings Synchronization should be enabled 
	in Amazon > Configuration > Synchronization.'); ?>
</div>