<div id="block_notice_amazon_template_general_general" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Channel Settings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('TODO TEXT'); ?>
</div>

<?php
    $formData = Mage::helper('M2ePro')->getGlobalValue('temp_data') ? Mage::helper('M2ePro')->getGlobalValue('temp_data') : array();

    $defaults = array(
        'marketplace_id' => -1,
        'account_id' => 0,
        'sku_mode' => Ess_M2ePro_Model_Amazon_Template_General::SKU_MODE_NONE,
        'sku_custom_attribute' => '',
        'general_id_mode' => Ess_M2ePro_Model_Amazon_Template_General::GENERAL_ID_MODE_NONE,
        'general_id_custom_attribute' => ''
    );
    $formData = array_merge($defaults, $formData);

    $isEdit = (bool)$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }
    //-----------------------------

</script>

<script type="text/javascript">

    // ie bug fix
    // ---------
    if (Prototype && Prototype.Browser.IE && varienLoaderHandler) {
        var loaderOnCompleteFunction = varienLoaderHandler.handler.onComplete;
        varienLoaderHandler.handler.onComplete = function() {

            loaderOnCompleteFunction();
            $$('select').each(function (el) {
                $(el).style.visibility = 'visible';
            });
        }
    }
    // ---------

    // Data for current tab
    //-----------------------------
    M2ePro.url.getMarketplacesForAccount = '<?php echo $this->getUrl('*/*/getMarketplacesForAccount'); ?>';

    M2ePro.formData.account_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['account_id']); ?>';
    M2ePro.formData.marketplace_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['marketplace_id']); ?>';

    Event.observe(window, 'load', function() {

        AmazonListingChannelSettingsHandlerObj = new AmazonListingChannelSettingsHandler();
        AmazonListingChannelSettingsHandlerObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Amazon_Template_General'); ?>');

        $('account_id').observe('change', AmazonListingChannelSettingsHandlerObj.account_id_change);
        $F('account_id') && $('account_id').simulate('change');

        $('marketplace_id').observe('change', AmazonListingChannelSettingsHandlerObj.marketplace_id_change);
        $F('marketplace_id') && $('marketplace_id').simulate('change');

        $('sku_mode').observe('change', AmazonListingChannelSettingsHandlerObj.sku_mode_change);

        $('sku_custom_attribute').observe('change', AmazonListingChannelSettingsHandlerObj.sku_custom_attribute_change);
        $F('sku_custom_attribute') && $('sku_custom_attribute').simulate('change');

        $('general_id_mode').observe('change', AmazonListingChannelSettingsHandlerObj.general_id_mode_change);

        $('general_id_custom_attribute').observe('change', AmazonListingChannelSettingsHandlerObj.general_id_custom_attribute_change);
        $F('general_id_custom_attribute') && $('general_id_custom_attribute').simulate('change');
    });
    //-----------------------------

</script>

<div class="entry-edit" id="magento_block_amazon_listing_channel_settings_general">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('General'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="account_id"><?php echo Mage::helper('M2ePro')->__('Amazon Account'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="account_id" name="account_id" class="required-entry">
                            <?php if (!$isEdit): ?>
                                <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($this->getData('accounts') as $account): ?>
                                <option value="<?php echo $account['id']; ?>" <?php if ($formData['account_id'] == $account['id']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($account['title']); ?></option>
                            <?php endforeach ?>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Amazon accounts you have already added in Configuration > Accounts.'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr id="marketplace_id_container" style="display: none;">
                    <td class="label">
                        <label for="marketplace_id"><?php echo Mage::helper('M2ePro')->__('Marketplace'); ?>: <span class="required">*</span></label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="marketplace_id" name="marketplace_id" class="required-entry select"></select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('Only the marketplaces chosen in Configuration > Marketplaces are shown for selection.'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_amazon_listing_channel_settings_source">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Source Settings'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label for="sku_mode"><?php echo Mage::helper('M2ePro')->__('SKU') ?>:</label>
                    </td>
                    <td class="value">
                        <select name="sku_mode" id="sku_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_General::SKU_MODE_NONE ?>" <?php if ($formData['sku_mode'] == Ess_M2ePro_Model_Amazon_Template_General::SKU_MODE_NONE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('None') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_General::SKU_MODE_DEFAULT ?>" <?php if ($formData['sku_mode'] == Ess_M2ePro_Model_Amazon_Template_General::SKU_MODE_DEFAULT) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Product SKU') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_General::SKU_MODE_CUSTOM_ATTRIBUTE ?>" <?php if ($formData['sku_mode'] == Ess_M2ePro_Model_Amazon_Template_General::SKU_MODE_CUSTOM_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute') ?></option>
                        </select>
                    </td>
                </tr>

                <tr id="sku_custom_attribute_container" <?php if ($formData['sku_mode'] != Ess_M2ePro_Model_Amazon_Template_General::SKU_MODE_CUSTOM_ATTRIBUTE) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="sku_custom_attribute"><?php echo Mage::helper('M2ePro')->__('SKU Attribute'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="sku_custom_attribute" name="sku_custom_attribute">
                            <?php if ($formData['sku_custom_attribute'] == ''): ?>
                                <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($this->getData('attributes') as $attribute): ?>
                                <option value="<?php echo $attribute['code']; ?>" <?php if ($formData['sku_custom_attribute'] == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                            <?php endforeach ?>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('TODO TEXT'); ?></span>
                        </p>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label for="general_id_mode"><?php echo Mage::helper('M2ePro')->__('ASIN/ISBN') ?>:</label>
                    </td>
                    <td class="value">
                        <select name="general_id_mode" id="general_id_mode">
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_General::GENERAL_ID_MODE_NONE ?>" <?php if ($formData['general_id_mode'] == Ess_M2ePro_Model_Amazon_Template_General::GENERAL_ID_MODE_NONE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('None') ?></option>
                            <option value="<?php echo Ess_M2ePro_Model_Amazon_Template_General::GENERAL_ID_MODE_CUSTOM_ATTRIBUTE ?>" <?php if ($formData['general_id_mode'] == Ess_M2ePro_Model_Amazon_Template_General::GENERAL_ID_MODE_CUSTOM_ATTRIBUTE) echo 'selected="selected"' ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute') ?></option>
                        </select>
                    </td>
                </tr>

                <tr id="general_id_custom_attribute_container" <?php if ($formData['general_id_mode'] != Ess_M2ePro_Model_Amazon_Template_General::GENERAL_ID_MODE_CUSTOM_ATTRIBUTE) echo ' style="display: none;"'; ?>>
                    <td class="label">
                        <label for="general_id_custom_attribute"><?php echo Mage::helper('M2ePro')->__('ASIN/ISBN Attribute'); ?>:</label>
                    </td>
                    <td class="value" style="width: auto;">
                        <select id="general_id_custom_attribute" name="general_id_custom_attribute">
                            <?php if ($formData['general_id_custom_attribute'] == ''): ?>
                                <option class="empty"></option>
                            <?php endif ?>
                            <?php foreach ($this->getData('attributes') as $attribute): ?>
                                <option value="<?php echo $attribute['code']; ?>" <?php if ($formData['general_id_custom_attribute'] == $attribute['code']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($attribute['label']); ?></option>
                            <?php endforeach ?>
                        </select>
                        <p class="note">
                            <span><?php echo Mage::helper('M2ePro')->__('TODO TEXT'); ?></span>
                        </p>
                    </td>
                </tr>

            </table>

        </div>
    </div>
</div>