<div id="<?php echo $this->getContainerId(); ?>" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Orders'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This page contains all orders imported from Amazon.
    Use Amazon Accounts dropdown to filter Amazon orders by accounts.<br/>
    If Magento Order, Invoice or / and Shipment was not created automatically,
    you can create them manually by using appropriate options in the Action dropdown.<br/><br/>
    <b>Note:</b> Automatic creation of Magento Orders, Invoices, and Shipments happens according to the Amazon Accounts
    settings in Amazon > Configuration > Amazon Accounts > Orders.'); ?>
</div>