<?php $hint = htmlspecialchars(trim($this->getField()->getHint())); ?>
<?php if ($this->getFieldValue()) $hint = false; ?>
<textarea name='<?php echo $this->getFieldName()?>' id='<?php echo $this->getFieldId()?>'
          class='<?php echo $this->getFieldClass()?>'
          style='<?php echo $this->getFieldStyle()?>' <?php if ($this->getField()->getDisabled()) { ?> disabled <?php } ?>
          <?php if($hint){?>onfocus="if (this.value == '<?php echo $hint?>') {this.value = '';}" onblur="if (this.value == '') {this.value = '<?php echo $hint?>';}"<?php } ?>><?php if ($hint) echo $hint; else echo htmlspecialchars($this->getFieldValue());?></textarea>
